theme: jekyll-theme-cayman
title: Paige Zimmerman's Homepage
description: Hello! My name is Paige, and I am an undergraduate at Lehigh University (class of 2024). I am pursuing a Marketing major, an Art Studio minor, and the Business Analytics Certificate. 
